# playbook.yml
- hosts: all
  tasks:
    - name: Copy the artifact
      copy:
        src: main
        dest: /home/laborant/main
        mode: '0755'      
      notify: Restart myapp.service

    - name: Create a unit file
      become: True        
      copy:
        src: myapp.service
        dest: /etc/systemd/system/myapp.service
      notify: Restart myapp.service

    - name: Ensure the service is running
      become: True
      ansible.builtin.systemd:
        name: myapp.service
        daemon_reload: true
        state: started

  handlers:
    - name: Restart myapp.service
      become: True
      ansible.builtin.systemd:
        name: myapp.service
        state: restarted